# Generated by Django 3.2.5 on 2021-08-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorplat_trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorplat',
            name='bvalue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='colorplat',
            name='gvalue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='colorplat',
            name='rvalue',
            field=models.IntegerField(default=0),
        ),
    ]
