# Generated by Django 3.2.5 on 2021-08-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorplat_trading', '0002_auto_20210801_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceRed', models.FloatField(default=0.0)),
                ('priceGreen', models.FloatField(default=0.0)),
                ('priceBlue', models.FloatField(default=0.0)),
                ('CreatedAt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ColorPlatPrices',
        ),
    ]
