# Generated by Django 3.2.5 on 2021-08-01 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colorplat_trading', '0003_auto_20210801_0639'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ColorPrices',
            new_name='ColorPrice',
        ),
    ]
