# Generated by Django 3.2.5 on 2021-08-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorplat_trading', '0004_rename_colorprices_colorprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorplat',
            name='CreatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
