# Generated by Django 3.2.5 on 2021-08-05 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colorplat_trading', '0005_colorplat_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('CreatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('fromaccount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_acc', to=settings.AUTH_USER_MODEL)),
                ('toaccount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_acc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
