# Generated by Django 3.2.5 on 2021-08-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorplat_trading', '0006_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='platsamount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trade',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
